name: Trigger auto deployment for rob-needs-help-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/rob-needs-help-server-AutoDeployTrigger-50af707c-bc8f-4cda-bc3e-13970b8ac856.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ROBNEEDSHELPSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROBNEEDSHELPSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROBNEEDSHELPSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Echo Dockerfile path
         run:  echo _dockerfilePath_

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hgthhn.azurecr.io
          registryUsername: ${{ secrets.ROBNEEDSHELPSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROBNEEDSHELPSERVER_REGISTRY_PASSWORD }}
          containerAppName: rob-needs-help-server
          resourceGroup: get-the-help-he-needs_group
          imageToBuild: hgthhn.azurecr.io/rob-needs-help-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


